// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stgiqplcprxaqzbeayyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0Z2lxcGxjcHJ4YXF6YmVheXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjQ1NjQsImV4cCI6MjA2MjgwMDU2NH0.agUr24w0os7fnVJcsy2L-3oohuih9EenWopjuxbmizw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);